### PR TITLE
chore(release): Update im-metadata to v3.0.0

### PR DESCRIPTION
**Pull request by anthonyringoet**

### CODE REVIEW

**Comment by anthonyringoet** [comment]
Bump im-metadata to fix https://github.com/Turistforeningen/node-s3-uploader/issues/10

**Comment by anthonyringoet** [comment]
Need to update the [size test](https://github.com/Turistforeningen/node-s3-uploader/blob/master/test/suite.coffee#L292) to return bytes

**Comment by Starefossen** [comment]
You got a merge commit in this branch. Can you do a rebase on master `git rebase origin/master` and `git push -f`.


A tip when creating new branches is to branch from the remote branch by `git checkout origin/master -b feature/awesome-new-feature` :smile:

**Comment by anthonyringoet** [comment]
Thanks for the tip, i'll go for a new pr.

**Pull request closed without merging**
