### PR TITLE
Refactor all CoffeeScript to vanilla JavaScript

### PR DESCRIPTION
**Pull request by Starefossen**
This PR implements #40 which replaces all CoffeeScript source code with vanilla JavaScript.

* [x] refactor src
* [x] refactor test
* [x] use jshint
* [x] fix remaining jshint errors
* [x] refactor variable declarations in test suite

### CODE REVIEW

**Comment by Starefossen** [comment]
@anthonyringoet Finally got around replacing all the CoffeeScript with vanilla JavaScript. Also added JSHint with the [airbnb](https://github.com/airbnb/javascript/blob/master/linters/jshintrc) style configuration.

I am thinking we could release v2.0.0-rc.1 when this gets merged, which will give us some time to test that nothing breaks while we implement the rest of the v2.0.0 features. What do you think?

**Comment by anthonyringoet** [comment]
Yes, totally agree with doing it that way. Nice work.

**Comment by Starefossen** [comment]
@anthonyringoet [`s3-uploader@2.0.0-rc.1`](https://github.com/Turistforeningen/node-s3-uploader/releases/tag/v2.0.0-rc.1) is out! :shipit:

**Comment by anthonyringoet** [comment]
nice, will test!

**Pull request merged**
