### PR TITLE
Upgrade aws-sdk dependency to ^2.2.9

### PR DESCRIPTION
**Pull request by Starefossen**
This PR upgrades `aws-sdk` dependency to `^2.2.9`

Signed-off-by: Hans Kristian Flaatten <hans.kristian.flaatten@turistforeningen.no>

### CODE REVIEW

**Comment by anthonyringoet** [comment]
@Starefossen, if you would like to automate these kind of requests, you could use http://greenkeeper.io

**Comment by Starefossen** [comment]
Thanks for this @anthonyringoet, have you tried it?

**Comment by anthonyringoet** [comment]
I'm using it and it's pretty handy.
You get automatic pull requests, tests run because of that.
Housekeeping is minimized to merging PR's or fixing it on that branch :)

**Comment by Starefossen** [comment]
Cool! We should definitely set that up for this project :smile: :rocket:

**Pull request merged**
